In [6]:
import numpy as np
#creating arrays
array1=np.array([1,2,3,4,5,6])
array2=np.array([[1,2,3],[4,5,6]])
array3=np.array([[[1,2,3],[4,5,6],[7,8,9]], [[1,1,1], [2,2,2], [3,3,3]],[[0,0,0],[0,0,0],[0,0,0]]])
print("array 1",array1)
print("array 2\n",array2)
print("array 3\n",array3)
print("sum of array is",np.sum(array1))
print("sum of mean is",np.mean(array1))
print(type(array1))
print(type(array2))


array 1 [1 2 3 4 5 6]
array 2
 [[1 2 3]
 [4 5 6]]
array 3
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 1 1]
  [2 2 2]
  [3 3 3]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
sum of array is 21
sum of mean is 3.5
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
import pandas as pd
series=pd.Series([1,2,3,4,5])
#creating  dataframe
data={'name':['alice','bob','charlie'],'age':[25,30,35],'address':['lubhoo','laltipur','lagankhel']}
df=pd.DataFrame(data)
print("series\n",series)
print("dataframe",df)
print(type(series))
print(type(data))
print(type(df))
print(type(data['name']))
print(type(data['age']))


series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
dataframe       name  age    address
0    alice   25     lubhoo
1      bob   30   laltipur
2  charlie   35  lagankhel
<class 'pandas.core.series.Series'>
<class 'dict'>
<class 'pandas.core.frame.DataFrame'>
<class 'list'>
<class 'list'>


In [8]:
array4=np.array([12,34,56,78,56,56])
print("elements wise addition of array is",array1 + array4)

elements wise addition of array is [13 36 59 82 61 62]


In [9]:
df['age plus ten']=df['age']+10

In [10]:
print("dataframe with new column is\n",df)

dataframe with new column is
       name  age    address  age plus ten
0    alice   25     lubhoo            35
1      bob   30   laltipur            40
2  charlie   35  lagankhel            45


In [11]:
#standrixation =newvalue=(orginal_value)/standars_deviation
#normalization(minmax)=a

In [12]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [13]:
data=np.array([[1,2],[2,3],[3,4],[4,5]])
scaler=MinMaxScaler()
normalized_data=scaler.fit_transform(data)
print("normalized data \n",normalized_data)

normalized data 
 [[0.         0.        ]
 [0.33333333 0.33333333]
 [0.66666667 0.66666667]
 [1.         1.        ]]


In [14]:
scaler=StandardScaler()
standerized_data =scaler.fit_transform(data)
print("standerized data is\n",standerized_data)

standerized data is
 [[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]


In [15]:
#feature engineering
#adding new feature
df['age_squared']=df['age']**2
df['age cubed']=df['age']**3
df['age_binned']=pd.cut(df['age'],bins=[20,30,40],labels=['20-30','30-40'])
print("the data frame with new features is\n",df)

the data frame with new features is
       name  age    address  age plus ten  age_squared  age cubed age_binned
0    alice   25     lubhoo            35          625      15625      20-30
1      bob   30   laltipur            40          900      27000      20-30
2  charlie   35  lagankhel            45         1225      42875      30-40


In [16]:
df.to_csv('output1.csv',header=True)


In [21]:
df.to_csv('output.csv',header=False)


In [2]:

info={'name':'jagadish','age':'22'}
info['level']=['bachelor','secoonday']
print(info)
info.update({'level'[2]:'primary'})
print(type(info['level']))


{'name': 'jagadish', 'age': '22', 'level': ['bachelor', 'secoonday']}
<class 'list'>
